### ISSUE TITLE
no Java box?

### ISSUE THREAD

**Issue by illtellyoulater** [bento-io/collection#172]
I select Android and I am not shown that I need to learn Java? Wait there is no Java box at all? :)

**Comment by JonHMChan** [comment]
There is: http://bentobox.io/java

**Comment by illtellyoulater** [comment]
Yes, my fault on that, but still, when I select Android, Java is not lit ? I thought highlighting was based on interconnection of technologies (like "you might also need to know CSS and JS if you are interested in HTML"), but when I click Android I get shown Swift (iOS) and Windows Phone, what use is this for then? I actually wanted to get involved in Android app development, should I now go for Windows Phone apps? :) no thanks :D

**Comment by JonHMChan** [comment]
Yes, that's by design. The boxes are meant to show a sequential or related step that is _not_ a prerequisite for that topic (see guidelines 8 and 9 for this). The reason for this rule is simple: the use case for most developers that come on the site is to figure out what to learn next. If I know Android, are there other technologies I should learn that are related? Android, iOS, and Windows Phone are clearly related technologies that are not prerequisites.

However, there is a valuable suggestion here: knowing what I would need to learn before Android is a valid use case. However, the use case for needing to know what's next is far more applicable given the UI. If there's an intuitive, well-designed way of differentiating next steps vs prerequisites, that's definitely on the table.

**Comment by illtellyoulater** [comment]
I think that would be a greatly useful feature. Many times when approaching something new, you don't know what you don't know! So you basically are lost in that phase of randomly stumbling here and there until you put together the pieces of the puzzle. It would rock if bento could serve the two purposes at the same time: suggesting something I might want to learn given I'm already interested in something, _and_ telling me what could be the prerequisites to know when willing to learn something new. Of course this can only be useful when trying to learn something not "atomic" (in opposition to what a language itself might be seen for), unless you further expand bento to include more abstract domains (i.e. object oriented programming so that when you click on Java it shows some introductory resources on OOP). But even without having to forcedly include some big compound subjects to serve this design pattern I think that this feature would still be useful for some of the current topics in bento.
I just recently recommended bento to someone wanting to know about the basis knowledge needed for modern web development, and for me its a very valuable resource.. so keep it up at its best :) I hope it gets more and more attention because it's a very interesting way of getting in the way of knowledge :)

**Comment by JonHMChan** [comment]
Something put in the queue of requests - prerequisites can be useful.
