### ISSUE TITLE
Suggestion: Should move to visual tree model

### ISSUE THREAD

**Issue by lukevmorris** [bento-io/collection#23]
I love the goal of this site.

I wonder whether it should be displayed in a tree format.  Similar to how many Talent Trees are displayed in RPGs, people should be able to start at a root (HTML), level that skill up (by moving through multiple links of varying difficulty), and then choose to move to a next-order technology (CSS).  Then repeat the process.

While still on the HTML level, you might see a couple of suggested technologies to move on to (CSS, JS).  The user can choose one of these (CSS), and the tree structure would change.  HTML would gray out, CSS would highlight, CSS links would appear.  Suggested technologies beyond CSS would appear.  JS would remain grayed out as an alternate branch off HTML.  Unless, as in this case, that technology would also make sense after the chosen progression.  That is, since JS might come after either HTML or CSS, the JS branch off HTML would disappear and JS branch off CSS would appear.

I think semi-masking later technologies will help present info in a bite-sized manner and prevent people from feeling overwhelmed.

Just some thoughts!

**Comment by JonHMChan** [comment]
This is a good suggestion. Each box is actually connected to others like a tree - they are considered nodes with a "$then" attribute that points to subsequent lessons. Visually, they do not appear that way; however, I do think think that keeping it in the grid format makes it easier for more experienced developers to jump to a particular resource if they like. I also don't want to hide certain areas so that the user also gets a chance to browse and explore as well!

**Comment by colemanfoley** [comment]
Jon, you're right, the exhaustive list should be available. But since the app is for beginners, the first thing it should show is a sequence of technologies to learn, instead of the exhaustive list. There could be a link to the complete list from the sequence view. Like in a book, the primary content is the narrative, that guides the reader through concepts in a certain order. But the glossary is always available to refer to.

**Comment by blast-hardcheese** [comment]
An easy first step would be creating an overlay with the current square in the center, dependencies on the top, and $then's on the bottom. The technical difficulties would be in animation, if required. The advantage is that you could effectively walk the tree by clicking on the squares at the top or bottom, fading+scrolling animations could serve to link the different states of the generated tree. This would satisfy #86, I think.

I really like the talent tree idea, especially since it would lend itself nicely to adding categories (as per #75) to provide further filters.

Another really powerful feature would be filtering by language (#116), since currently there's a lot of noise (especially for people just starting out). Assuming the talent tree, level 0 would be visible given the default filter, only treeing out 2 or 3 blocks. Beyond that, just a single box with a number, representing the rest of the tree (the number would be how many blocks have been hidden).

**Comment by JonHMChan** [comment]
I believe Learning Tracks solves a lot of issues discussed here. Closed until we want to revisit and enhance.
