### ISSUE TITLE
CNAME error when Pull requested

### ISSUE THREAD

**Issue by aungthurhahein** [bento-io/collection#56]
Got this error when pull requested:

The page build failed with the following error:

CNAME already taken: www.bentobox.io

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions please contact us at https://github.com/contact.

**Comment by colemanfoley** [comment]
You're getting that error because this repo is set up to publish using [GitHub Pages](http://pages.github.com/). Whatever is in the gh-pages branch attempts to publish to either
A) a custom domain, if one is specified in the CNAME file
B) (your GitHub user name).github.io/(project name) For you, it would be: aungthurhahein.github.io/bento
So, if you delete the CNAME file, commit, then push to your fork's gh-pages branch again, you will be able to find your fork at aungthurhahein.github.io/bento
Source: [GitHub Pages help page](https://help.github.com/articles/user-organization-and-project-pages#project-pages)

**Comment by JonHMChan** [comment]
thanks for the clarification!
